### ISSUE TITLE
Add support for minions mode.

### ISSUE THREAD

**Issue by DanGNU** [gexplorer/simple-modeline#1]
There is [this](https://github.com/tarsius/minions) very good mode for showing minor modes, do you think is possible to add it here?

**Comment by gexplorer** [comment]
Good idea, I did use it for a while I just didn't use it lately so i didn't include compatibility with it. I will most definitely check out what do I have to do in order to make simple mode line compatible with it.

**Comment by gexplorer** [comment]
Hi @DanGNU sorry for the delay. I'm releasing a new version to make adding and removing segments easier. I'll check out hyoyoung's pr and see how can I use minions mode.

**Comment by gexplorer** [comment]
I'm afraid I can't easily add support for minions mode out of the box because by default **simple-modeline** shows major an minor modes separated so it doesn't directly use the **mode-line-modes** variable, which is what minions-mode replaces in the modeline.

But the good news is that with the latest version, changing the layout of the modeline is much easier. You can control which segments your modeline displays with the customization variable ***simple-modeline-segments***.

So with a simple snippet like this wrapping **minions-mode-line-modes**:

```elisp
(defun simple-modeline-segment-minions ()
  "Displays the current major and minor modes with minions-mode in the mode-line."
  (concat " " (format-mode-line minions-mode-line-modes)))
```

Is just a matter of removing **simple-modeline-segment-minor-modes** and **simple-modeline-segment-major-mode** from the modeline and inserting **simple-modeline-segment-minions** wherever you want.
