### ISSUE TITLE
reserved right (offset of right segments) calc seems to be off

### ISSUE THREAD

**Issue by birdspider** [gexplorer/simple-modeline#8]
Hi,

there is a space after major mode, which I assume is due to something being off calculating the "middle" spaces

![simple-modeline-offset-calc](https://user-images.githubusercontent.com/370960/110212507-e7dd4200-7e9b-11eb-998b-89f831026dbd.jpg)

this does not appear in the terminal only in gui mode.  Font is `ttf-iosevka`

EDIT: I did try with `ttf-iosevka-term` and `ttf-iosevka-fixed` with the same outcome. Finally I did change the modeline faces `:height` from 0.85 to 1.0 and that solved it. So the height of the modeline font was the culprit.

**Comment by gexplorer** [comment]
I'm glad it sorted out easily. Anyway could you tell me what to do to have the same behavior? Is it just a matter of changing the height of the mode lone face?

**Comment by gexplorer** [comment]
I'm afraid there's no way out of this. I've seen a few packages that align things to the right fail whenever the face used is not the same size as the default. I guess it's expected because the way of aligning things in emacs is based on characters, so whenever some of those characters are different sizes it's not possible to correctly align.
